paths:
  /products/all/{page}/10:
    get:
      summary: Mostra 10 produtos por página.
      tags:
        - Produtos - visualização
      parameters:
        - name: page
          in: path
          required: true
          description: Número da página
          schema:
            type: number
      responses:
        '200':
            description: Produtos retornados do banco de dados com sucesso.
        '500':
            description: Erro interno do servidor, geralmente ocorrido por uma query errada ou falha de conexão com banco de dados.
  /products/{pid}:
    get:
      summary: Encontra o produto pelo seu id.
      tags:
        - Produto - visualização
      parameters:
        - name: pid
          in: path
          required: true
          description: ID do produto que deseja visualizar
      responses:
        '200':
            description: Produto encontrado no banco de dados.
        '500':
            description: Erro interno do servidor, geralmente ocorrido por uma query errada ou falha de conexão com banco de dados.
    delete:
      summary: Deleta um produto pelo seu id.
      tags:
        - Produtos - deletar
      parameters:
        - name: pid
          in: path
          required: true
          description: ID do produto
      responses:
        '200':
            description: Produto deletado do banco de dados.
        '401':
            description: Usuário não autorizado para deletar produtos.
        '500':
            description: Erro interno do servidor.
    put:
      summary: Atualiza um produto pelo seu id.
      tags:
        - Produtos - atualização
      parameters:
        - name: pid
          in: path
          required: true
          description: ID do produto
          schema:
              type: string
      requestBody:
        require: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/product'
      responses:
        '200':
            description: Produto atualizado no banco de dados.
        '401':
            description: Usuário não autorizado para atualizar produtos.
        '500':
            description: Erro interno do servidor.
  /products:
    post:
      summary: Cadastra um novo produto.
      tags:
        - Produtos - cadastro
      requestBody:
        require: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/product'
      responses:
        '200':
            description: Novo produto cadastrado no banco de dados.
        '401':
            description: Usuário não autorizado para cadastrar produtos.
        '500':
            description: Erro interno do servidor.
components:
  schemas:
    product:
      type: object
      properties:
        title:
          type: string
          description: Nome do produto
        category:
          type: string
          description: Enquadra o produto em uma categoria
        description:
          type: string
          description: Descrição do produto
        price:
          type: number
          description: Valor do produto em reais
        code:
          type: number
          description: Código do produto
        thumbnail:
          type: string
          description: Nome do arquivo em .png        
        stock:
          type: number
          description: Quantidade do produto em estoque
        status:
          type: string
          description: Informa se o produto está true ou false        
      example:
        title: Saia
        description: Mini saia jeans, azul marinho, com costura em beje
        price: 45
        thumbnail: saia29.png
        code: 13
        stock: 24
        status: true
        category: saias